---
- hosts: "{{ target }}"
  gather_facts: no
  tasks:
    - name: get host id
      shell: echo {{ inventory_hostname}} | awk -F_ '{print $NF}'
      register: host_id
    - name: copy staker.crt to local machine
      fetch:
        src: /home/ubuntu/.avalanchego/staking/staker.crt
        dest: "{{ nodesDirPath }}/{{ host_id.stdout }}/"
        flat: true
    - name: copy staker.key to local machine
      fetch:
        src: /home/ubuntu/.avalanchego/staking/staker.key
        dest: "{{ nodesDirPath }}/{{ host_id.stdout }}/"
        flat: true
    - name: copy signer.key to local machine
      fetch:
        src: /home/ubuntu/.avalanchego/staking/signer.key
        dest: "{{ nodesDirPath }}/{{ host_id.stdout }}/"
        flat: true
