---
- hosts: "{{ target }}"
  gather_facts: no
  tasks:
    - name: get host id
      shell: echo {{ inventory_hostname}} | awk -F_ '{print $NF}'
      register: host_id
    - name: ensures dest dir exists
      file: 
        path: "/home/ubuntu/.avalanchego/staking/"
        state: directory
        recurse: yes
    - name: copy staking files to remote machine
      copy:
        src: "{{ item }}"
        dest: /home/ubuntu/.avalanchego/staking/
      loop:
        - "{{ nodesDirPath }}{{ host_id.stdout }}/staker.crt"
        - "{{ nodesDirPath }}{{ host_id.stdout }}/staker.key"
        - "{{ nodesDirPath }}{{ host_id.stdout }}/signer.key"
