---
- hosts: "{{ target }}"
  gather_facts: no
  tasks:
    - name: copy node config to local machine
      fetch:
        src: /home/ubuntu/.avalanchego/configs/node.json
        dest: "{{ ansibleDir }}/{{ inventory_hostname }}/node.json"
        flat: true
