---
- hosts: "{{ target }}"
  gather_facts: no
  tasks:
    - name: install jq
      shell: |
        jq --version && exit
        sudo apt install jq -y
        jq --version
    - name: set devnet flags
      shell: |
          jq '."genesis-file" = "/home/ubuntu/.avalanchego/configs/genesis.json"' /home/ubuntu/.avalanchego/configs/node.json > node.tmp.json
          mv node.tmp.json /home/ubuntu/.avalanchego/configs/node.json
          jq '."network-id" = "'{{ networkID }}'"' /home/ubuntu/.avalanchego/configs/node.json > node.tmp.json
          mv node.tmp.json /home/ubuntu/.avalanchego/configs/node.json
          jq '."bootstrap-ips" = "'{{ bootstrapIPs }}'"' /home/ubuntu/.avalanchego/configs/node.json > node.tmp.json
          mv node.tmp.json /home/ubuntu/.avalanchego/configs/node.json
          jq '."bootstrap-ids" = "'{{ bootstrapIDs }}'"' /home/ubuntu/.avalanchego/configs/node.json > node.tmp.json
          mv node.tmp.json /home/ubuntu/.avalanchego/configs/node.json
