---
- hosts: "{{ target }}"
  gather_facts: no
  tasks:
    - name: install avalanchego
      shell: |
        wget -nd -m https://raw.githubusercontent.com/ava-labs/avalanche-docs/master/scripts/avalanchego-installer.sh
        chmod 755 avalanchego-installer.sh
        ./avalanchego-installer.sh --ip static --rpc private --state-sync on --fuji --version {{ avalancheGoVersion }}
    - name: stop node if devnet
      shell: sudo systemctl stop avalanchego
      when: setDevnet == "true"
    - name: install avalanche cli
      shell: |
        wget -nd -m https://raw.githubusercontent.com/ava-labs/avalanche-cli/main/scripts/install.sh
        chmod 755 install.sh
        ./install.sh -n
        mkdir .avalanche-cli
        echo "{"MetricsEnabled":false}" > .avalanche-cli/config
