---
- hosts: "{{ target }}"
  gather_facts: no
  tasks:
    - name: download monitoring script
      shell: wget -nd -m https://raw.githubusercontent.com/ava-labs/avalanche-monitoring/main/grafana/monitoring-installer.sh
    - name: modify permission for monitoring script
      shell: chmod 755 monitoring-installer.sh
    - name: set up Prometheus
      shell: ./monitoring-installer.sh --1
    - name: install Grafana
      shell: ./monitoring-installer.sh --2
    - name: set up node_exporter
      shell: ./monitoring-installer.sh --3
    - name: set up dashboards
      shell: ./monitoring-installer.sh --4