---
- hosts: "{{ target }}"
  gather_facts: no
  tasks:
    - name: copy monitoring script to cloud server
      copy:
        src: "{{ monitoringScriptPath }}"
        dest: /home/ubuntu/
    - name: modify permission for monitoring script
      shell: chmod 755 monitoring-separate-installer.sh
    - name: set up Prometheus
      shell: ./monitoring-separate-installer.sh --1
    - name: install Grafana
      shell: ./monitoring-separate-installer.sh --2
    - name: set up node_exporter
      shell: ./monitoring-separate-installer.sh --3 "{{ arg1 }}" "{{ arg2 }}"
    - name: set up dashboards
      shell: ./monitoring-separate-installer.sh --4